<?php

namespace AppBundle\Repository;

/**
 * CommentImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentImageRepository extends \Doctrine\ORM\EntityRepository
{
}
