<?php

namespace AppBundle\Repository;

/**
 * ReportImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportImageRepository extends \Doctrine\ORM\EntityRepository
{
}
