imports:
    - { resource: "parameters.yml" }
    - { resource: "@AppBundle/Resources/config/object_wrappers.yml" }
    - { resource: "@AppBundle/Resources/config/authorization.yml" }
    - { resource: "@AppBundle/Resources/config/parameters.yml" }
    - { resource: "security.yml" }
    - { resource: "services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        dql:
          string_functions:
            group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# app/config/config.yml
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...

#nelmio_api_doc: ~

#jms_serializer:
#    enable_short_alias: false

fos_rest:
    serializer:
        serialize_null: true
    exception:
        enabled: true
#        messages:
#            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
#        exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
        exception_controller: 'AppBundle\Controller\ExceptionController::showAction'
    view:
        formats:
            json: true
#            rss: false # removing them will also work
#            xml: true
            jsonp: true
        view_response_listener: true
        mime_types:
            json: ['application/json', 'application/x-json']
            jsonp: ['application/jsonp']
            rss: ['application/rss+xml']
            jpg: ['image/jpeg']
            png: ['image/png']
        jsonp_handler:
            callback_param:       callback
            mime_type:            application/javascript+jsonp

nelmio_cors:
        defaults:
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/':
                allow_credentials: true
                allow_origin: ['*']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
                max_age: 3600
            '^/':
                allow_credentials: false
                origin_regex: false
                #allow_origin: ['^http://localhost:[0-9]+']
                allow_origin: ['*']
                # allow_headers: ['X-Custom-Auth']
                allow_headers: ['*']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE','OPTIONS']
                max_age: 3600